### ISSUE TITLE
[Spike] Generate items automatically

### ISSUE THREAD

**Issue by Ericli0708** [penguin-statistics/frontend-v2#269]
### What problem does this feature solve?
For today's Arkplanner page, I have to enter how many items I need and how many items I have manually which is a really unpleasant experience. Also this page cannot store my data. Once I leave the page like go to report the items drop, all the data gone which is also a frustrating experience.

### What does the proposed API look like?
In the Arkplanner page, if select an operator and elite step the Arkplanner can generate the items I need automatically that would be better. 

EX version: Furthermore, if it can intergrate with the drops report and I don't need to enter the items change twice that would be a lot better.

**Comment by GalvinGao** [comment]
Thanks for reporting this feature. We have planned to add persistence for ArkPlanner in the next release.

The request of adding a quick entry for some operator upgrade requirements need more discussion since it seems to be a redundant feature to other sites, but if it is not adding too much development overhead we will consider adding it.

**Comment by Ericli0708** [comment]
主要是昨天灰猫写的工具箱入驻bigfun以后刷图规划功能不再能用，而且发了issue过去以后他说这个问题不能被解决，刷图规划功能会被移除，所以希望你们能添加这一功能。先谢了。
