### ISSUE TITLE
Bad results in ArkPlanner for Global servers

### ISSUE THREAD

**Issue by Idran** [penguin-statistics/frontend-v2#337]
### Environment
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36`

### URL
`https://penguin-stats.io/planner`

### Steps to reproduce
Run ArkPlanner for anything involving higher level materials in US servers.

### What is expected?
Only stages that are actually released in Global will be included in calculated results, or you will have the option to filter out stages not yet released from the Exclude Stages option.

### What is actually happening?
The Exclude Stages option only displays stages released in Global, but stages from chapters 6 and 7 will still be included in the ArkPlanner results with no way to exclude them.

**Comment by SStembridge** [comment]
Just ran into this problem. Had to switch the server back to CN in order to uncheck all the chapter 6 and 7 stages, otherwise they were included in the results even though they don't show up in the excluded stages section when on US server.

Looking through the rest of the open issues though, I think that this is the same problem as #315 (using google translate)

**Comment by GalvinGao** [comment]
Thanks for reporting this issue. After we've done refactoring Planner this shall be fixed ;) :heart:
