### ISSUE TITLE
Timestamp system is flawed

### ISSUE THREAD

**Issue by bill88t** [penguin-statistics/frontend-v2#447]
### Environment
`Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0`

### URL
`https://penguin-stats.io/report/recognition`

### Steps to reproduce
Upload screenshots from iphone.
Timestamp does not get preserved.
Timestamp error.

### What is expected?
To be able to upload screenshots.

### What is actually happening?
It rejects them as the timestamps are too close.

---
Any simple checksum would have worked just fine.

**Comment by bill88t** [comment]
The level and xp in a screenshot should never be identical. You could use that

**Comment by martinwang2002** [comment]
> The level and xp in a screenshot should never be identical. You could use that

I have proposed this idea during development, but the problem is that we cannot distinguish screenshots with level 120 (currently the maximum level).

**Comment by GalvinGao** [comment]
Sorry for the delay in response, but we have disabled the timestamp verification a month ago to ensure sample count and to help mitigate this issue. Without the timestamp verification the accuracy of dataset is still solid enough since we have implemented a fingerprint de-duplication feature on Day 0. :D
