### ISSUE TITLE
Double click on zone/stage/icon will jump to incorrect page

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#57]
### Environment
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36`

### URL
`https://penguin-stats.io/`

#### Report
1. In report page, **double click** on a zone. User will go to step 3 immediately without selecting any stage.
![image](https://user-images.githubusercontent.com/25188552/63206135-a55ad700-c063-11e9-83b6-75be1000b8e8.png)
2. Go back to step 1 (In stepper, not in this doc. The same below), choose a zone with **single click**. Then **double click** (be fast!) on a stage. Nothing is shown below as if the stage was not selected.
![image](https://user-images.githubusercontent.com/25188552/63206140-c02d4b80-c063-11e9-8df5-7f788e82c3c5.png)
3. Go back to step 1, **double click** on a zone. It will show the report page for the stage you selected previously.
![image](https://user-images.githubusercontent.com/25188552/63206170-329e2b80-c064-11e9-86c9-3ed62ff572ad.png)

#### Result (by stage)
The weird behavior is similar to report page.

#### Result (by item)
In result (by item) page, **double click** (be fast!) on an item. Nothing is shown below as if the item was not selected.
![image](https://user-images.githubusercontent.com/25188552/63206194-9fb1c100-c064-11e9-9668-65a11277bed2.png)

### What is expected?
N/A

### What is actually happening?
N/A

**Comment by GalvinGao** [comment]
Successfully reproduced. The cause of the bug is that the `step` will be added on every click of the choice elements (zone/stage). So on:
1. in the first case, after interaction the *expected* data will be `step = 2`, but the *actual data* is `step = 3`.
2. in the second case, before interaction `step = 2`; After interaction, the *expected* data is `step = 3`, but the *actual data* is `step = 4` so it shows no element.
3. in the third case, before interaction `step = 1`; After interaction, the *expected* data is `step = 2`, but the *actual data* is `step = 3` so it shows no element.
